import type { ToolDefinition } from './types';

const srcStub = (name: string) => [{ name, type: 'stub' as const, licenseNote: 'integration pending' }];

export const clinicalToolRegistry: ToolDefinition[] = [
  { id:'icd-search', titleTR:'ICD-10 / ICD-11 Tanı Kodlama Asistanı', category:'terminology', membershipTier:'basic', frequency:'very_common', riskLevel:'low', descriptionTR:'WHO ICD adapter + lokal ICD-10 TR arama', inputs:[{key:'query',labelTR:'Tanı metni',type:'string',required:true}], outputSchema:{type:'object'}, implementationType:'external_api', sources:[{name:'WHO ICD / ICD-10 TR',type:'official_api'}], status:'implemented' },
  { id:'snomed-search', titleTR:'SNOMED CT Klinik Terim Arama', category:'terminology', membershipTier:'elite', frequency:'common', riskLevel:'high_requires_validated_data', descriptionTR:'Snowstorm adapter', inputs:[{key:'term',labelTR:'Terim',type:'string',required:true}], outputSchema:{type:'object'}, implementationType:'external_api', sources:srcStub('SNOMED CT'), status:'implemented' },
  { id:'loinc-mapper', titleTR:'LOINC Laboratuvar Kod Eşleştirici', category:'lab', membershipTier:'pro', frequency:'common', riskLevel:'moderate', descriptionTR:'LOINC eşleştirme', inputs:[{key:'testName',labelTR:'Test adı',type:'string',required:true}], outputSchema:{type:'object'}, implementationType:'external_api', sources:srcStub('LOINC'), status:'implemented' },
  { id:'rxnorm-search', titleTR:'RxNorm / RxTerms İlaç Arama', category:'medication', membershipTier:'pro', frequency:'common', riskLevel:'moderate', descriptionTR:'RxNorm arama', inputs:[{key:'drug',labelTR:'İlaç',type:'string',required:true}], outputSchema:{type:'object'}, implementationType:'external_api', sources:srcStub('RxNorm'), status:'implemented' },
  { id:'titck-drug-search', titleTR:'Türkiye Ruhsatlı İlaç ve KÜB/KT Arama', category:'medication', membershipTier:'pro', frequency:'common', riskLevel:'moderate', descriptionTR:'TİTCK lokal dataset', inputs:[{key:'query',labelTR:'İlaç adı',type:'string',required:true}], outputSchema:{type:'object'}, implementationType:'hybrid', sources:[{name:'TİTCK sample',type:'local_dataset'}], status:'implemented' },
  { id:'drug-interaction-check', titleTR:'İlaç-İlaç Etkileşim Kontrolü', category:'medication', membershipTier:'elite', frequency:'common', riskLevel:'high_requires_validated_data', descriptionTR:'Lisanslı veri gerekli', inputs:[{key:'drugs',labelTR:'İlaç listesi',type:'array',required:true}], outputSchema:{type:'object'}, implementationType:'licensed_api_required', sources:srcStub('Licensed interaction DB'), status:'implemented' },
  { id:'allergy-contraindication', titleTR:'Alerji / Kontrendikasyon Uyarı Modülü', category:'medication', membershipTier:'elite', frequency:'common', riskLevel:'high_requires_validated_data', descriptionTR:'Demo kural motoru', inputs:[{key:'drugs',labelTR:'İlaç listesi',type:'array',required:true}], outputSchema:{type:'object'}, implementationType:'hybrid', sources:[{name:'Demo allergy rules',type:'internal_protocol'}], status:'implemented' },
  { id:'renal-dose-warning', titleTR:'Böbrek Fonksiyonuna Göre Doz Uyarısı', category:'medication', membershipTier:'elite', frequency:'common', riskLevel:'high_requires_validated_data', descriptionTR:'eGFR/CrCl + lisans uyarısı', inputs:[{key:'age',labelTR:'Yaş',type:'number',required:true}], outputSchema:{type:'object'}, implementationType:'hybrid', sources:srcStub('Licensed renal dose DB'), status:'implemented' },
  { id:'pregnancy-lactation-safety', titleTR:'Gebelik / Laktasyon İlaç Güvenliği', category:'medication', membershipTier:'elite', frequency:'common', riskLevel:'high_requires_validated_data', descriptionTR:'Kaynak gerektirir', inputs:[{key:'drug',labelTR:'İlaç',type:'string',required:true}], outputSchema:{type:'object'}, implementationType:'licensed_api_required', sources:srcStub('Pregnancy/Lactation DB'), status:'implemented' },
  { id:'lab-pre-interpretation', titleTR:'Laboratuvar Sonucu Ön Yorumlama', category:'lab', membershipTier:'pro', frequency:'common', riskLevel:'moderate', descriptionTR:'Lokal referans aralığı tabanlı', inputs:[{key:'testName',labelTR:'Test',type:'string',required:true}], outputSchema:{type:'object'}, implementationType:'local_rules', sources:[{name:'Local lab references',type:'local_dataset'}], status:'implemented' },
  { id:'critical-lab-alert', titleTR:'Kritik Laboratuvar Değer Alarmı', category:'lab', membershipTier:'basic', frequency:'very_common', riskLevel:'moderate', descriptionTR:'Kritik eşik uyarısı', inputs:[{key:'testName',labelTR:'Test',type:'string',required:true}], outputSchema:{type:'object'}, implementationType:'local_rules', sources:[{name:'Critical threshold config',type:'internal_protocol'}], status:'implemented' },
  { id:'guideline-search', titleTR:'Guideline Arama ve Özetleme Asistanı', category:'guideline', membershipTier:'pro', frequency:'common', riskLevel:'moderate', descriptionTR:'NICE/RAG interface', inputs:[{key:'question',labelTR:'Soru',type:'string',required:true}], outputSchema:{type:'object'}, implementationType:'rag_required', sources:srcStub('Guideline provider'), status:'implemented' },
  { id:'differential-checklist', titleTR:'Ayırıcı Tanı Checklist Tool’u', category:'guideline', membershipTier:'elite', frequency:'common', riskLevel:'potential_samd_review', descriptionTR:'Kontrollü checklist', inputs:[{key:'complaint',labelTR:'Ana şikayet',type:'string',required:true}], outputSchema:{type:'object'}, implementationType:'rag_required', sources:[{name:'Controlled checklist',type:'internal_protocol'}], status:'implemented' },
  { id:'red-flags', titleTR:'Red Flag / Acil Yönlendirme Kontrolü', category:'guideline', membershipTier:'basic', frequency:'very_common', riskLevel:'low', descriptionTR:'Acil red-flag sorgulama', inputs:[{key:'complaint',labelTR:'Şikayet',type:'string',required:true}], outputSchema:{type:'object'}, implementationType:'local_rules', sources:[{name:'Emergency red flag rules',type:'internal_protocol'}], status:'implemented' },
  { id:'imaging-appropriateness', titleTR:'Görüntüleme Uygunluk Asistanı', category:'guideline', membershipTier:'pro', frequency:'common', riskLevel:'moderate', descriptionTR:'Görüntüleme seçenekleri', inputs:[{key:'scenario',labelTR:'Klinik senaryo',type:'string',required:true}], outputSchema:{type:'object'}, implementationType:'rag_required', sources:srcStub('ACR/NICE style'), status:'implemented' },
  { id:'antibiotic-stewardship', titleTR:'Antibiyotik Stewardship Asistanı', category:'guideline', membershipTier:'elite', frequency:'common', riskLevel:'potential_samd_review', descriptionTR:'Protokol checklist', inputs:[{key:'focus',labelTR:'Enfeksiyon odağı',type:'string',required:true}], outputSchema:{type:'object'}, implementationType:'hybrid', sources:[{name:'Local stewardship protocol',type:'internal_protocol'}], status:'implemented' },
  { id:'immunization-catchup', titleTR:'Aşı Takvimi / Catch-up Kontrolü', category:'guideline', membershipTier:'pro', frequency:'common', riskLevel:'moderate', descriptionTR:'Türkiye takvimi stub', inputs:[{key:'birthDate',labelTR:'Doğum tarihi',type:'date',required:true}], outputSchema:{type:'object'}, implementationType:'local_rules', sources:[{name:'TR immunization config stub',type:'local_dataset'}], status:'implemented' },
  { id:'patient-education', titleTR:'Hasta Bilgilendirme Metni Oluşturucu', category:'documentation', membershipTier:'basic', frequency:'very_common', riskLevel:'low', descriptionTR:'Template', inputs:[{key:'topic',labelTR:'Konu',type:'string',required:true}], outputSchema:{type:'object'}, implementationType:'local_rules', sources:[{name:'Internal templates',type:'internal_protocol'}], status:'implemented' },
  { id:'after-visit-summary', titleTR:'Muayene Sonrası Özet / After Visit Summary', category:'documentation', membershipTier:'basic', frequency:'very_common', riskLevel:'low', descriptionTR:'Template', inputs:[{key:'diagnosis',labelTR:'Tanı',type:'string',required:true}], outputSchema:{type:'object'}, implementationType:'local_rules', sources:[{name:'Internal templates',type:'internal_protocol'}], status:'implemented' },
  { id:'referral-discharge-draft', titleTR:'Epikriz / Konsültasyon / Sevk Mektubu Taslağı', category:'documentation', membershipTier:'basic', frequency:'common', riskLevel:'low', descriptionTR:'Structured draft', inputs:[{key:'complaint',labelTR:'Şikayet',type:'string',required:true}], outputSchema:{type:'object'}, implementationType:'local_rules', sources:[{name:'Internal templates',type:'internal_protocol'}], status:'implemented' },
  { id:'bmi-bsa', titleTR:'BMI / BSA / İdeal Kilo Hesaplayıcı', category:'calculator', membershipTier:'basic', frequency:'very_common', riskLevel:'low', descriptionTR:'BMI/BSA', inputs:[{key:'heightCm',labelTR:'Boy',type:'number',required:true}], outputSchema:{type:'object'}, implementationType:'local_formula', sources:[{name:'BMI/Mosteller',type:'formula_reference'}], status:'implemented' },
  { id:'egfr-crcl', titleTR:'eGFR / Cockcroft-Gault / CrCl Hesaplayıcı', category:'calculator', membershipTier:'basic', frequency:'very_common', riskLevel:'moderate', descriptionTR:'Renal fonksiyon', inputs:[{key:'age',labelTR:'Yaş',type:'number',required:true}], outputSchema:{type:'object'}, implementationType:'local_formula', sources:[{name:'CKD-EPI/Cockcroft-Gault',type:'formula_reference'}], status:'implemented' },
  { id:'cardiovascular-risk', titleTR:'Kardiyovasküler Risk Hesaplayıcı', category:'calculator', membershipTier:'pro', frequency:'common', riskLevel:'moderate', descriptionTR:'SCORE2/ASCVD adapter', inputs:[{key:'age',labelTR:'Yaş',type:'number',required:true}], outputSchema:{type:'object'}, implementationType:'external_api', sources:srcStub('SCORE2/ASCVD adapter'), status:'implemented' },
  { id:'cha2ds2-hasbled', titleTR:'CHA2DS2-VASc / HAS-BLED Tool’u', category:'calculator', membershipTier:'basic', frequency:'very_common', riskLevel:'low', descriptionTR:'AF risk', inputs:[{key:'age',labelTR:'Yaş',type:'number',required:true}], outputSchema:{type:'object'}, implementationType:'local_formula', sources:[{name:'CHA2DS2/HAS-BLED',type:'formula_reference'}], status:'implemented' },
  { id:'wells-perc-ddimer', titleTR:'Wells / PERC / Yaşa Göre D-dimer Tool’u', category:'calculator', membershipTier:'basic', frequency:'very_common', riskLevel:'low', descriptionTR:'VTE olasılık', inputs:[{key:'age',labelTR:'Yaş',type:'number',required:true}], outputSchema:{type:'object'}, implementationType:'local_rules', sources:[{name:'Wells/PERC',type:'formula_reference'}], status:'implemented' },
  { id:'curb65-crb65', titleTR:'CURB-65 / CRB-65 Pnömoni Şiddet Tool’u', category:'calculator', membershipTier:'basic', frequency:'common', riskLevel:'low', descriptionTR:'Pnömoni şiddeti', inputs:[{key:'age',labelTR:'Yaş',type:'number',required:true}], outputSchema:{type:'object'}, implementationType:'local_formula', sources:[{name:'CURB65',type:'formula_reference'}], status:'implemented' },
  { id:'news2-qsofa', titleTR:'NEWS2 / qSOFA Akut Kötüleşme Tool’u', category:'calculator', membershipTier:'basic', frequency:'common', riskLevel:'moderate', descriptionTR:'Akut kötüleşme', inputs:[{key:'rr',labelTR:'Solunum sayısı',type:'number',required:true}], outputSchema:{type:'object'}, implementationType:'local_formula', sources:[{name:'NEWS2/qSOFA',type:'formula_reference'}], status:'implemented' },
  { id:'child-pugh-meldna', titleTR:'Child-Pugh / MELD-Na Karaciğer Skorları', category:'calculator', membershipTier:'pro', frequency:'common', riskLevel:'moderate', descriptionTR:'Karaciğer skoru', inputs:[{key:'bilirubin',labelTR:'Bilirubin',type:'number',required:true}], outputSchema:{type:'object'}, implementationType:'local_formula', sources:[{name:'Child-Pugh/MELD-Na',type:'formula_reference'}], status:'implemented' },
  { id:'pediatric-growth', titleTR:'Pediatrik Büyüme Persentil / Z-score Tool’u', category:'calculator', membershipTier:'pro', frequency:'common', riskLevel:'moderate', descriptionTR:'Sample dataset ile', inputs:[{key:'ageMonths',labelTR:'Ay',type:'number',required:true}], outputSchema:{type:'object'}, implementationType:'local_rules', sources:[{name:'Sample growth chart',type:'local_dataset'}], status:'implemented' },
  { id:'pregnancy-dating-edd', titleTR:'Gebelik Haftası / EDD Hesaplayıcı', category:'calculator', membershipTier:'basic', frequency:'very_common', riskLevel:'low', descriptionTR:'SAT tabanlı EDD', inputs:[{key:'lmp',labelTR:'SAT',type:'date',required:true}], outputSchema:{type:'object'}, implementationType:'local_formula', sources:[{name:'ACOG dating',type:'formula_reference'}], status:'implemented' }
];
