import type { ToolDefinition } from './types';
const stub=(name:string)=>[{name,type:'stub' as const}];
export const clinicalToolRegistry: ToolDefinition[] = [
{id:'icd-search',titleTR:'ICD-10 / ICD-11 Tanı Kodlama Asistanı',category:'terminology',membershipTier:'basic',frequency:'very_common',riskLevel:'low',descriptionTR:'ICD eşleştirme',inputs:[],outputSchema:{type:'object'},implementationType:'external_api',sources:[{name:'WHO ICD + ICD-10 TR',type:'official_api'}],status:'implemented'},
{id:'snomed-search',titleTR:'SNOMED CT Klinik Terim Arama',category:'terminology',membershipTier:'elite',frequency:'common',riskLevel:'high_requires_validated_data',descriptionTR:'SNOMED arama',inputs:[],outputSchema:{type:'object'},implementationType:'external_api',sources:stub('Snowstorm'),status:'integration_stub'},
{id:'loinc-mapper',titleTR:'LOINC Laboratuvar Kod Eşleştirici',category:'lab',membershipTier:'pro',frequency:'common',riskLevel:'moderate',descriptionTR:'LOINC eşleştirme',inputs:[],outputSchema:{type:'object'},implementationType:'external_api',sources:stub('LOINC'),status:'integration_stub'},
{id:'rxnorm-search',titleTR:'RxNorm / RxTerms İlaç Arama',category:'medication',membershipTier:'pro',frequency:'common',riskLevel:'moderate',descriptionTR:'RxNorm arama',inputs:[],outputSchema:{type:'object'},implementationType:'external_api',sources:stub('RxNorm'),status:'integration_stub'},
{id:'titck-drug-search',titleTR:'Türkiye Ruhsatlı İlaç ve KÜB/KT Arama',category:'medication',membershipTier:'pro',frequency:'common',riskLevel:'moderate',descriptionTR:'TİTCK arama',inputs:[],outputSchema:{type:'object'},implementationType:'hybrid',sources:[{name:'TITCK sample',type:'local_dataset'}],status:'integration_stub'},
{id:'drug-interaction-check',titleTR:'İlaç-İlaç Etkileşim Kontrolü',category:'medication',membershipTier:'elite',frequency:'common',riskLevel:'high_requires_validated_data',descriptionTR:'Etkileşim',inputs:[],outputSchema:{type:'object'},implementationType:'licensed_api_required',sources:stub('Licensed DB'),status:'requires_license'},
{id:'allergy-contraindication',titleTR:'Alerji / Kontrendikasyon Uyarı Modülü',category:'medication',membershipTier:'elite',frequency:'common',riskLevel:'high_requires_validated_data',descriptionTR:'Alerji',inputs:[],outputSchema:{type:'object'},implementationType:'hybrid',sources:stub('Demo rules'),status:'integration_stub'},
{id:'renal-dose-warning',titleTR:'Böbrek Fonksiyonuna Göre Doz Uyarısı',category:'medication',membershipTier:'elite',frequency:'common',riskLevel:'high_requires_validated_data',descriptionTR:'Renal doz',inputs:[],outputSchema:{type:'object'},implementationType:'hybrid',sources:stub('License pending'),status:'requires_license'},
{id:'pregnancy-lactation-safety',titleTR:'Gebelik / Laktasyon İlaç Güvenliği',category:'medication',membershipTier:'elite',frequency:'common',riskLevel:'high_requires_validated_data',descriptionTR:'Gebelik güvenliği',inputs:[],outputSchema:{type:'object'},implementationType:'licensed_api_required',sources:stub('License pending'),status:'requires_license'},
{id:'lab-pre-interpretation',titleTR:'Laboratuvar Sonucu Ön Yorumlama',category:'lab',membershipTier:'pro',frequency:'common',riskLevel:'moderate',descriptionTR:'Lab yorum',inputs:[],outputSchema:{type:'object'},implementationType:'local_rules',sources:[{name:'local lab ranges',type:'local_dataset'}],status:'integration_stub'},
...['critical-lab-alert','guideline-search','differential-checklist','red-flags','imaging-appropriateness','antibiotic-stewardship','immunization-catchup','patient-education','after-visit-summary','referral-discharge-draft','bmi-bsa','egfr-crcl','cardiovascular-risk','cha2ds2-hasbled','wells-perc-ddimer','curb65-crb65','news2-qsofa','child-pugh-meldna','pediatric-growth','pregnancy-dating-edd'].map((id)=>({id,titleTR:id,category:(['patient-education','after-visit-summary','referral-discharge-draft'].includes(id)?'documentation':['guideline-search','differential-checklist','red-flags','imaging-appropriateness','immunization-catchup'].includes(id)?'guideline':'calculator') as any,membershipTier:(['cardiovascular-risk','child-pugh-meldna','pediatric-growth','guideline-search','imaging-appropriateness','immunization-catchup'].includes(id)?'pro':['differential-checklist','antibiotic-stewardship'].includes(id)?'elite':'basic') as any,frequency:'common' as const,riskLevel:(['differential-checklist','antibiotic-stewardship'].includes(id)?'potential_samd_review':'low') as any,descriptionTR:id,inputs:[],outputSchema:{type:'object'},implementationType:(['bmi-bsa','egfr-crcl','cha2ds2-hasbled','wells-perc-ddimer','curb65-crb65','news2-qsofa','pregnancy-dating-edd','child-pugh-meldna'].includes(id)?'local_formula':'local_rules') as any,sources:stub(id),status:(['bmi-bsa','egfr-crcl','cha2ds2-hasbled','wells-perc-ddimer','curb65-crb65','news2-qsofa','pregnancy-dating-edd','patient-education','referral-discharge-draft','icd-search'].includes(id)?'implemented':'integration_stub') as any}))
];
